CREATE DATABASE customer_behavior

USE customer_behavior;

SELECT * FROM customer;

--Q1. What is the total revenue generated by male vs. female customers?
SELECT 
gender,
SUM(purchase_amount) as revenue
From customer
GROUP BY gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT customer_id,
purchase_amount
FROM customer
WHERE discount_applied = 'Yes' AND purchase_amount >= (select AVG(purchase_amount) FROM customer);


-- Q3. Which are the top 5 products with the highest average review rating?
SELECT TOP 5
item_purchased,
ROUND(AVG(review_rating),2) average_product_rating
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
--These 5 products can be highlghted in market campaigns and can be sold at high price.

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT
 shipping_type,
 AVG(purchase_amount) averge_spend_shipping
FROM customer
WHERE shipping_type IN('Standard','Express')
GROUP BY shipping_type

--Business should spend more on Express Shipping 

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.

SELECT 
subscription_status,
COUNT(customer_id) total_customers,
ROUND(AVG(purchase_amount),2) average_spend,
ROUND(SUM(purchase_amount),2) total_spend
FROM customer
GROUP BY subscription_status
ORDER BY average_spend , total_spend DESC
--one's who does not subscribe to the services spend more 


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT top 5
item_purchased,
ROUND(SUM (case when discount_applied = 'Yes' THEN 1 ELSE 0 END) *100/ COUNT(*) ,2) AS discount_percentages
FROM customer
GROUP by item_purchased
ORDER BY discount_percentages DESC
--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
WITH customer_type AS
(
SELECT customer_id,
CASE WHEN previous_purchases = 1  THEN 'New'
 WHEN previous_purchases between 2 and 10 THEN 'Returning'
ELSE 'Loyal'
END AS customer_segments 
FROM customer
)
SELECT 
customer_segments,
COUNT(*) AS customer_count
FROM customer_type
GROUP BY customer_segments
order by customer_count DESC


--Q8. What are the top 3 most purchased products within each category? 
WITH item_count AS(
SELECT 
category,
item_purchased,
count(*) as total_orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(*) DESC) AS item_rank
FROM customer
group by category, item_purchased) 
SELECT 
item_rank,
category,
item_purchased,
total_orders 
FROM item_count
WHERE item_rank <=3;

--Q9.Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT 
subscription_status,
COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;


--Q10. What is the revenue contribution of each age group? 
SELECT age_group,
sum(purchase_amount) as revenue_by_age
FROM customer
GROUP BY age_group
